version: "3"
services:
  nginx:
    build: ./
    image: nginx:alpine-module-echo
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./app1:/var/www/html/app1:rw
      - ./app2:/var/www/html/app2:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro